### ISSUE TITLE
faststart

### ISSUE THREAD

**Issue by svnpenn** [Martchus/tageditor#11]
TagEditor seems to have no way to set or even detect faststart (moov before mdat). Please resolve, thank you.

**Comment by svnpenn** [comment]
https://github.com/axiomatic-systems/Bento4/issues/105

**Comment by Martchus** [comment]
You can use the GUI to view the element structure.

Setting this is also possible (as stated in [README#tag-position](https://github.com/Martchus/tageditor#tag-position)). Just use `--tag-pos front --force` to enable 'faststart' (as you call it). The option `--index-pos` has no influence on MP4 files because in MP4 files tags and index are tied. But be aware that this will likely cause a rewrite of the file (which you wanted to avoid in the other issue). (Of course, if there's enough space in front of the file, the file is not rewritten.)

**Comment by svnpenn** [comment]
Thanks for the response, but there seems to be no way to actually use the
*--tag-pos* option:

~~~
$ tageditor set title=Juliet --files tmp.m4a
Setting tag information for "tmp.m4a" ...
Changes have been applied.

$ tageditor set title=Juliet --tag-pos front --force --files tmp.m4a
Unable to parse arguments. The specified argument "tmp.m4a" is unknown and will
be ignored. See --help for available commands.

$ tageditor set --tag-pos front --force --files tmp.m4a
Unable to parse arguments. The specified argument "tmp.m4a" is unknown and will
be ignored. See --help for available commands.
~~~

**Comment by svnpenn** [comment]
@Martchus thanks for the response, but there seems to be no way to actually use
the *--tag-pos* option:

~~~
$ tageditor set title=Juliet --files tmp.m4a
Setting tag information for "tmp.m4a" ...
Changes have been applied.

$ tageditor set title=Juliet --tag-pos front --force --files tmp.m4a
Unable to parse arguments. The specified argument "tmp.m4a" is unknown and will
be ignored. See --help for available commands.

$ tageditor set --tag-pos front --force --files tmp.m4a
Unable to parse arguments. The specified argument "tmp.m4a" is unknown and will
be ignored. See --help for available commands.
~~~

**Comment by Martchus** [comment]
I experimented a little bit with the argument parser and might have messed it. Which build do you use? If your using the latest devel build for Windows try to switch back to the latest release.

**Comment by svnpenn** [comment]
None of the devel builds work, and I dont know where to get the release version
you are talking about:

~~~
$ tageditor-devel-1/tageditor set title=juliet --tag-pos front --force --files tmp.m4a
Segmentation fault

$ tageditor-devel-2/tageditor set title=juliet --tag-pos front --force --files tmp.m4a
Unable to parse arguments. The specified argument "tmp.m4a" is unknown and will
See --help for available commands.

$ tageditor-devel-3/tageditor set title=juliet --tag-pos front --force --files tmp.m4a
Unable to parse arguments. The specified argument "tmp.m4a" is unknown and will
See --help for available commands.

$ tageditor-devel-4/tageditor set title=juliet --tag-pos front --force --files tmp.m4a
Unable to parse arguments. The specified argument "tmp.m4a" is unknown and will
See --help for available commands.
~~~

**Comment by Martchus** [comment]
This is bad. Seems like the arg parser broke in devel-2 and before it was broken anyways due some other reason.

The release can be found under https://martchus.no-ip.biz/repo/win/dynamic/stable. There is no statically linked binary for release so far and it might not be the latest release. (I don't put so much effort in the Windows version.)

But it might have been broken already then and I just didn't notice.

**Comment by svnpenn** [comment]
Testing is broken:

http://martchus.no-ip.biz/repo/win/dynamic/testing/x86_64-w64-mingw32-ownstuff.zip

~~~
$ tageditor set title=juliet --tag-pos front --force --files tmp.m4a
Segmentation fault
~~~

stable too:

http://martchus.no-ip.biz/repo/win/dynamic/stable/x86_64-w64-mingw32-ownstuff.zip

~~~
$ tageditor set title=juliet --tag-pos front --force --files tmp.m4a
Unable to parse arguments. The given argument "--force" is unknown.
See --help for available commands.
~~~

**Comment by Martchus** [comment]
Ok, I'll look into it later. Does it work via GUI?

**Comment by svnpenn** [comment]
Sorry but I cant do any more testing on this now. Besides, if the command line version doesnt work, then my interest in the project is done

**Comment by Martchus** [comment]
Should be fixed with latest commits.
Here is a Windows build including the latest changes: https://martchus.no-ip.biz/repo/win/static/tageditor-devel-5-static-x86_64-w64-mingw32.tar.xz

**Comment by svnpenn** [comment]
I will try to test it after work. Having a robust tool for reading/writing MP4/M4A tags is very important. Frankly all the tools out there except yours are awful:

http://github.com/svnpenn/a/blob/41c8fc8/md/2016-11-13-mp4-m4a-metadata.md

For years I have been using some combination of the above tools, would be nice one simple command line tool that does it all.

**Comment by svnpenn** [comment]
@Martchus I am not seeing it?

~~~
$ devel-5/tageditor --info --files hasty\ boom\ alert\ 128k\ aac.m4a
Technical information for "hasty boom alert 128k aac.m4a":
  Container format: MPEG-4 Part 14
    Document type                 dash
    Duration                      5 min 15 s 303 ms
    Creation time                 2015-06-30 10:39:44
    Modification time             2015-06-30 10:39:44
  Tracks:
    ID                            1
    Name                          SoundHandler
    Type                          Audio
    Format                        Advanced Audio Coding Low Complexity Profile
    Abbreviation                  MPEG-4 AAC-LC
    Raw format ID                 mp4a
    Size                          4.72 MiB (4949807 byte)
    Duration                      5 min 15 s 303 ms
    Channel config                2 channels: front-left, front-right
    Bitrate                       122.645 kbit/s
    Bits per sample               16
    Sampling frequency            44100 Hz
    Sample count                  13579
    Creation time                 2015-06-30 10:39:44
    Modification time             2015-06-30 10:39:44
~~~

**Comment by svnpenn** [comment]
@Martchus Using this file:

~~~
youtube-dl --format m4a --fixup warn --output tinderbox.m4a wz8lOJFIaCE
~~~

it will not work at first:

~~~
$ tageditor -i -f tinderbox.m4a
Technical information for "tinderbox.m4a":
  Container format: MPEG-4 Part 14
    Document type                 dash
    Duration                      4 min 57 s 423 ms
    Creation time                 2015-02-18 17:15:20
    Modification time             2015-02-18 17:15:20
~~~

but then if I write a tag:

~~~
$ tageditor -s title=uniform -f tinderbox.m4a
Setting tag information for "tinderbox.m4a" ...
Changes have been applied.
~~~

now it works:

~~~
$ tageditor -i -f tinderbox.m4a
Technical information for "tinderbox.m4a":
  Container format: MPEG-4 Part 14
    Document type                 dash
    Duration                      4 min 57 s 423 ms
    Creation time                 2015-02-18 17:15:20
    Modification time             2015-02-18 17:15:20
    Tag position                  before data
~~~

TagEditor should be able to read the Tag position without having to write to the
file

**Comment by Martchus** [comment]
Probably the file has no tag in the first place. Then it wouldn't make any sense to tell where it is placed.

I also plan to show the same for the index position (which is always the same as the tag position in MP4 files) and this will be shown every time then.

**Comment by svnpenn** [comment]
Using this script:

~~~
#!/usr/bin/awk -f
/moov/ {
  print "faststart (moov before mdat)"
  exit
}
/mdat/ {
  print "not faststart (moov after mdat)"
  exit 1
}
~~~

http://github.com/svnpenn/a/blob/939fe4e/etc/faststart.awk

it works before doing anything:

~~~
$ faststart.awk tinderbox.m4a
faststart (moov before mdat)
~~~

while TagEditor fails before writing a tag:

~~~
$ tageditor -i -f tinderbox.m4a
Technical information for "tinderbox.m4a":
  Container format: MPEG-4 Part 14
    Document type                 dash
    Duration                      4 min 57 s 423 ms
    Creation time                 2015-02-18 17:15:20
    Modification time             2015-02-18 17:15:20
~~~

Now after writing a tag:

~~~
$ tageditor -s title=uniform --tag-pos back --force -f tinderbox.m4a
Setting tag information for "tinderbox.m4a" ...
Changes have been applied.
~~~

they both work:

~~~
$ faststart.awk tinderbox.m4a
not faststart (moov after mdat)
~~~

~~~
$ tageditor -i -f tinderbox.m4a
Technical information for "tinderbox.m4a":
  Container format: MPEG-4 Part 14
    Document type                 dash
    Duration                      4 min 57 s 423 ms
    Creation time                 2015-02-18 17:15:20
    Modification time             2015-02-18 17:15:20
    Tag position                  after data
~~~

this is not right. TagEditor should work without having to write to the file
first.

**Comment by svnpenn** [comment]
Also notice, Bento4 confirms that the unmodified file has every needed to
confirm yes or no to faststart:

~~~
$ mp4dump tinderbox.m4a | grep '^\['
[ftyp] size=8+16
[moov] size=8+560
[sidx] size=12+380
[moof] size=8+3528
[mdat] size=8+157425
~~~

**Comment by Martchus** [comment]
Yes and this will be shown as index position by the Tag Editor as soon as I implement it. I distinguish this because I also support Matroska where the index might be before and the tags after the data.

Your script isn't very reliable because it wouldn't work if moov or mdat occur somewhere else in the file.

BTW: Interesting that you like using UNIX shell scripts but using Windows, though.

**Comment by svnpenn** [comment]
Ah, so what I am calling "faststart" you are calling "index position", which has not been implemented yet, got it.

Awk is a powerful tool, and Windows doesnt have anything like it. However Cygwin offers it

**Comment by svnpenn** [comment]
@Martchus I have some issues with the README. You say this:

> So for forcing faststart the following options are required:

>     tageditor set --tag-pos front --force

However this is wrong for 2 reasons:

1. While it would be nice, you cannot currently move the tags without setting
   them at the same time:

        $ tageditor set --tag-pos back --force -f tinderbox.m4a
        Error: No fields/attachments have been specified.

2. As you said yourself, faststart is set by *--index-pos*, not *--tag-pos*

**Comment by Martchus** [comment]
1. Right, the error should be a warning.
2. Also correct, I will change this.

**Comment by Martchus** [comment]
This is fixed now.

**Comment by svnpenn** [comment]
@Martchus something is fucky with --index-pos. Take a file that already has
faststart, and you can move the positions to the back with --tag-pos:

~~~
$ tageditor set --tag-pos back --force -f bravo.m4a
$ tageditor -i -f bravo.m4a
Tag position                  after data
Index position                after data
~~~

then you can move them back to the front with --index-pos:

~~~
$ tageditor set --index-pos front --force -f bravo.m4a
$ tageditor -i -f bravo.m4a
Tag position                  before data
Index position                before data
~~~

How after that first invocation of --index-pos, the file is now fucked. You
cannot change the positions now with either method:

~~~
$ tageditor set --tag-pos back --force -f bravo.m4a
$ tageditor -i -f bravo.m4a
Tag position                  before data
Index position                before data
~~~

~~~
$ tageditor set --index-pos back --force -f bravo.m4a
$ tageditor -i -f bravo.m4a
Tag position                  before data
Index position                before data
~~~

This is with devel-6, not sure if this has already been fixed on master.

**Comment by svnpenn** [comment]
Confirmed this is failing on master too

**Comment by Martchus** [comment]
Should be fixed.

**Comment by svnpenn** [comment]
@Martchus I hate to say it but that commit https://github.com/Martchus/tageditor/commit/65ed11f0f1e20ada30556849ae60c5512239ec80 does not seem to have fixed it

**Comment by svnpenn** [comment]
@Martchus actually hold that, i might have used the wrong library - i will try again

**Comment by svnpenn** [comment]
@Martchus i was using old library after recompile so i thought that might have caused the problem - but problem persists even with fresh libraries - that makes sense because you didnt change the libraries with this latest commit

**Comment by Martchus** [comment]
What about commit https://github.com/Martchus/tagparser/commit/eafbda8233bd4d7040c9205c6071d87850f92c46?

**Comment by svnpenn** [comment]
Either way - just now done fresh clone and build of everything and problem persists

**Comment by Martchus** [comment]
Can you provide your sample file?

**Comment by svnpenn** [comment]
~~~
youtube-dl --format m4a --fixup warn wz8lOJFIaCE
~~~

**Comment by Martchus** [comment]
```
ERROR: wz8lOJFIaCE: YouTube said: This video is not available.
```

So you likely have a DASH file. Disabling 'faststart' for DASH is not possible. Maybe the detection (what you get via `-i`) is broken in this case.

**Comment by svnpenn** [comment]
arg - region restriction - here is the file

http://drive.google.com/open?id=0B7CLEEZ2V1_AWUo1YkY3dHNuS2M

**Comment by svnpenn** [comment]
@Martchus region restriction - here is the file

http://drive.google.com/open?id=0B7CLEEZ2V1_AWUo1YkY3dHNuS2M

1. Yes, it is a DASH file

2. It appears faststart can be disabled, at least until --index-pos gets
   involved:

~~~
$ tageditor set --tag-pos back --force -f bravo.m4a
Warning: No fields/attachments have been specified.
Setting tag information for "bravo.m4a" ...
Changes have been applied.

$ tageditor -i -f bravo.m4a
Technical information for "bravo.m4a":
  Container format: MPEG-4 Part 14
    Document type                 dash
    Duration                      4 min 57 s 423 ms
    Creation time                 2015-02-18 17:15:20
    Modification time             2015-02-18 17:15:20
    Tag position                  after data
    Index position                after data
~~~

**Comment by Martchus** [comment]
As far as I see it the problem is that `tageditor set --tag-pos back --force -f bravo.m4a` 'works' in the first place.

Putting index/tags at the end of the DASH file is actually no problem for the tagparser library. However, all player I tried refuse to play after doing so. Hence creating such files should be prevented by the library. This has been the case already, but not in all cases. Should be fixed in commit https://github.com/Martchus/tagparser/commit/a6b2d106558e2d0f1a62a803b89f8735b1278174.

**Comment by Martchus** [comment]
I should also mention that DASH variant of MP4 is likely not the container format you want to use for you local music library. This format is meant for streaming and not handled well by all applications (even VLC player can not deal with DASH correctly). Also, the file structure of regular MP4 makes seeking much easier.

**Comment by svnpenn** [comment]
@Martchus I can confirm everything is working as expected, thank you
